### ISSUE TITLE
Sign-in Implementation in explorer broken

### ISSUE THREAD

**Issue by bingbinglee** [idena-network/idena-explorer#13]
Browser: Chrome 54

Steps to reproduce:
1. Open scan.idena.io
2. Click on sign-in with Idena 
3. The sign-in window opens and asks permission to open idena desktop app
4. In the idena desktop the following dialog appears with localhost address instead of the right callback URL

<img width="718" alt="Screen Shot 2020-05-16 at 5 26 22 PM" src="https://user-images.githubusercontent.com/62775041/82130626-04887c00-979b-11ea-9c2c-fc5860ae883e.png">

5. If you go back to the idena explorer sign-in page, do a refresh and then click the URL again then the callback resolves fine. 

----

**Comment by geatb** [comment]
Same issue on Chrome Canary 85.0.4148.0

**Comment by midenaio** [comment]
@bingbinglee Can not reproduce the issue. Please try out the latest client version: [0.10.0](https://github.com/idena-network/idena-desktop/releases)

**Comment by bingbinglee** [comment]
interesting. could be resolved in new client. Will try this.

**Comment by bingbinglee** [comment]
This works in new client. closing this
