### ISSUE TITLE
Link to previous epoch on flip committees

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-explorer#15]
When we click on an address of a user being part of qualification committee or challenged identities in flip page, it takes us to previous epoch's flips of that user.

https://scan.idena.io/flip/bafkreickzlnjcvvu3wfmiya3s5otzjrfsnfo4u6b3ilukjxazc5xe5fdg4 (flip for epoch #45 validation).

But address links point to epoch #44 flips (probably cause it was created in previous epoch).

**Comment by busimus** [comment]
Addressed in PR #14.

**Comment by KruciferX** [comment]
Thanks.
