### ISSUE TITLE
Transaction page in explorer shows wrong receiver

### ISSUE THREAD

**Issue by KruciferX** [idena-network/idena-explorer#8]
![image](https://user-images.githubusercontent.com/52136297/82046023-65875580-96b0-11ea-841a-c13ee1ac7c06.png)

![image](https://user-images.githubusercontent.com/52136297/82046063-7e900680-96b0-11ea-8ba0-7d6062b64c9c.png)

https://scan.idena.io/transaction/0xaf1c9477a8ac847a77c8d17cd156701f6fb0153c3e400122e296b296754873ca

**Comment by midenaio** [comment]
Fixed. Thank you @KruciferX
